### ISSUE TITLE
It's interesting.

### ISSUE THREAD

**Issue by hgalytoby** [JacobLinCool/MyselfBBS-Desktop#3]
I have a similar idea. 👍

**Comment by JacobLinCool** [comment]
Excellent!

This project is not finished yet. (favorite list, auto-clean, etc.) Unfortunately, in the past few months I do not have much time on it, so I almost forget all of the details about the core functionalities. 😢 

But if you have any questions or ideas of the project, feel free to open an issue or pull request. I'll reply or review them in my free time.

Thanks!
